# Generated by Django 5.1.1 on 2024-10-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.IntegerField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='strategies.tradingstrategy')),
            ],
        ),
    ]
