# Generated by Django 5.1.2 on 2024-12-13 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_token', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('level_number', models.PositiveIntegerField()),
                ('main_percentage', models.FloatField(blank=True, null=True)),
                ('main_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('main_target', models.FloatField(blank=True, null=True)),
                ('percentage_down', models.FloatField(blank=True, null=True)),
                ('hedging_quantity', models.IntegerField(blank=True, null=True)),
                ('hedging_limit_price', models.FloatField(blank=True, max_length=6, null=True)),
                ('hedging_limit_quantity', models.IntegerField(blank=True, null=True)),
                ('is_skip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceQuantityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_quantity_data', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_order_status', models.IntegerField(choices=[(0, 'None'), (1, 'COMPLETED'), (2, 'PENDING'), (3, 'CANCELLED')], default=0)),
                ('order_side', models.CharField(blank=True, max_length=10, null=True)),
                ('exit_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_order_status', models.IntegerField(choices=[(0, 'None'), (1, 'COMPLETED'), (2, 'PENDING'), (3, 'CANCELLED')], default=0)),
                ('is_entry', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.orderlevel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_instrument', models.CharField(blank=True, max_length=255, null=True)),
                ('original_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hedging', models.BooleanField(default=False)),
                ('hedging_instrument', models.CharField(blank=True, max_length=255, null=True)),
                ('hedging_strike_distance', models.IntegerField(blank=True, default=0, null=True)),
                ('hedging_quantity', models.IntegerField(blank=True, null=True)),
                ('hedging_limit_price', models.FloatField(blank=True, null=True)),
                ('hedging_limit_quantity', models.IntegerField(blank=True, null=True)),
                ('hedge_limit_order_time_for_convert_from_lo_to_mo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderlevel',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_levels', to='accounts.orderstrategy'),
        ),
    ]
