# Generated by Django 5.1.2 on 2024-12-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_orderlevel_hedging_limit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
