# Generated by Django 5.1.5 on 2025-01-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orders_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(max_length=1000),
        ),
    ]
