# Generated by Django 5.1.5 on 2025-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accesstoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstrategy',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
