# Generated by Django 5.1.5 on 2025-02-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_orderstrategy_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.orderlevel'),
        ),
    ]
